### ISSUE TITLE
In case of readonly errors it should create a sentry

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-changes#38]

**Comment by glasserc** [comment]
Could you elaborate on this? I think this might be similar to what we encountered in production last week, but I could be wrong.

Another possibility is to strip collections which raise an error during collection_timestamp from the changes feed.

/cc @bqbn

**Comment by Natim** [comment]
After the migration we did were we changed the way we were storing timestamps, we tried to access, using the readonly instances (kinto.stage.mozaws.net), some collections and especially the monitor/changes one.

However since this stack is readonly, kinto wasn't able to create the timestamp entry which resulted in a 503.

The fix was to access it once through the writer (kinto-writer.stage.mozaws.net) to initialize the collection timestamp.

I believe this bug has been fixed with Kinto 8.1.4 release.

**Comment by glasserc** [comment]
This issue is still important -- https://github.com/Kinto/kinto/pull/1475 fixes the case where there is an existing timestamp, but if there isn't one, we just totally fail. Now, it's possible to access it once through the writer, but it will fail until you do. Would it be good to skip ones that don't have a timestamp?

**Comment by Natim** [comment]
> Would it be good to skip ones that don't have a timestamp?

I would rather make sure to call monitor changes once on startup in the writer so that we can be sure that it is ready or on the migrate call maybe?

**Comment by glasserc** [comment]
@bqbn points out that the writer wasn't "starting up" at the time; we had created a collection using kinto-wizard, without taking down or migrating any nodes. Remembering to run kinto-wizard leaves a (small) window where requests fail and there's nothing we can do about it.

While it's true that this is specific to our use case, the fact that no last_modified is present is a strong signal that the collection is empty and has never been used, which means it cannot by definition have had any changes, which is why I think it's safe to drop it from the changes feed. I understand the concern that this will lead to mysterious situations where a collection has been "created" but doesn't show up in kinto-changes for cryptic reasions, so maybe we should put a log message in when we otherwise drop a collection? Would that make you feel better about this change?

**Comment by bqbn** [comment]
Yeah, so what happened last week was that we ran "kinto-wizard" to load the permission file into the database. Shortly after that we see increased amount of 50X on -prod.

The solution was we had to run 
```
curl -i https://<kinto_writer_server>/v1/buckets/monitor/collections/changes/records
```
to make the 50X go away.
